# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    # Flake8 Plugin
-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    - id: flake8
    # Black Plugin
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    - id: black
    # Ruff Plugin
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.262'
    hooks:
    - id: ruff
    # Bandit Plugin
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
    - id: bandit
